protected/controllers/HomeController.php
<?php
class HomeController extends FController
{

	public function actionLogin() {
		$service = Yii::app()->request->getQuery('service');
	    if (isset($service)) {
	        $authIdentity = Yii::app()->eauth->getIdentity($service);
	        $authIdentity->redirectUrl = Yii::app()->user->returnUrl;
	        $authIdentity->cancelUrl = $this->createAbsoluteUrl('home/login');
	        
	        if ($authIdentity->authenticate()) {
	            $identity = new ServiceUserIdentity($authIdentity);
	            
	            // Успешный вход
	            if ($identity->authenticate()) {
	                Yii::app()->user->login($identity);
	                
	                // Специальный редирект с закрытием popup окна
	                $authIdentity->redirect();
	            }
	            else {
	                // Закрываем popup окно и перенаправляем на cancelUrl
	                $authIdentity->cancel();
	            }
	        }
	        
	        // Что-то пошло не так, перенаправляем на страницу входа
	        $this->redirect(array('home/login'));
	    }
	    
	    $this->render('login');
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	public function actionIndex()
	{
		Yii::app()->params->section(array('page'=>'home'));

		//Yii::app()->config->init = 'homepage';
		// Считываем что отображать на главной
		list($_controller, $_action, $_view) = Yii::app()->params['{home}']['display'];
		if(!empty($_controller)) {
			list($_controller, $_action, $_view) = Yii::app()->params['{home}']['display'];
			//list($_controller, $_action, $_view) = explode(" ", $home);
		} else {
			$_controller = 'default';
		}

		// Открываем выбранное отображение
		if(!empty($_controller) && $_controller != 'default' && (list($controller) = Yii::app()->createController($_controller))) {

			$controller->metaKeywords = $this->metaKeywords;
			$controller->metaDescription = $this->metaDescription;
			$controller->metaTitle = $this->metaTitle;

			if(Yii::app()->params['{home}']['layout'] !== '')
				$controller->layout = (Yii::app()->params['{home}']['layout'])?Yii::app()->params['{home}']['layout']:Yii::app()->params['{app}']['layout'];

			if(!empty($_action) && $action = $controller->createAction($_action)) {
				if(!empty($_view))
					$action->runWithParams(array('id'=>$_view));
				else
					$action->run();
			} else {
				$controller->run($controller->defaultAction);
			}
		} else {
			$this->render('index');
		}
	}

	public function actionError()
	{
	    if($error = Yii::app()->errorHandler->error)
	        $this->render('error', $error);
	}
	
}

protected/views/layouts/index.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/form.css" />
	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/styles.css" />
	<!-- Иконки -->
	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/font-awesome-4.1.0/css/font-awesome.min.css">
	<!-- Шрифты -->
	<link href='<?=Yii::app()->getbaseUrl(true)?>/public/css/font/PoiretOne.css' rel='stylesheet' type='text/css'> <!-- 'Poiret One', cursive -->
	<link href='<?=Yii::app()->getbaseUrl(true)?>/public/css/font/OpenSans.css' rel='stylesheet' type='text/css'> <!-- 'Open Sans' -->
	<link href='<?=Yii::app()->getbaseUrl(true)?>/public/css/font/OpenSansCondensed.css' rel='stylesheet' type='text/css'><!-- 'Open Sans Condensed', sans-serif -->
	<? Yii::app()->clientScript->registerCoreScript('jquery'); ?>
	<? Yii::app()->clientScript->registerScriptFile('/public/js/menu.js', CClientScript::POS_HEAD); ?>
	<? Yii::app()->clientScript->registerScriptFile('/public/js/scalert.js', CClientScript::POS_HEAD); ?>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<?php

	Yii::app()->clientScript->registerScript('scm_ajaxmenu', '
		var scm_url = "'.Yii::app()->createAbsoluteUrl('admin/ajax/menuupdate').'";
	', CClientScript::POS_HEAD);

?>
<body>
	<div id="container">
		<div id="mainback">
			<div id="backgr">


			</div>
			<div id="messeges">
				<i class="fa fa-sort-desc"></i>

			</div>
			
		</div>
		<div id="sidenav">
			<div id="sidemenu">
				<div id="supmenu">
					<?php $this->widget('zii.widgets.CMenu',array(
						'encodeLabel'=>false,
						'items'=>Yii::app()->params['AdminMenu'],
					));
					?>
				</div>
				<div id="submenu">

				</div>
			</div>
		</div>
		<header>
			<div id="logo">
				<?=CHtml::link('<span class="sun">Sun<span class="code">Code</span><span class="cms">.CMS</span></span>',array('/admin/home')); ?>
			</div>
			<div id="tools">
				<?=CHtml::link('<i class="fa fa-home"></i>', array('/home/index'), array('target'=>'_blank')); ?>
				<?=CHtml::link('<i class="fa fa-sign-out"></i>', array('/admin/home/logout')); ?>
			</div>
				<?php $this->widget('zii.widgets.CMenu',array(
						'encodeLabel'=>false,
						'activateParents'=>true,
						'items'=>Yii::app()->params['AdminMenu'],
						'htmlOptions'=>array('class'=>'navi'),
					));
				?>
		</header>
		<div id="content">
			<div class="heading">
			<h1><?=$this->title; ?></h1>
			<?php $this->widget('zii.widgets.CBreadcrumbs', array('homeLink'=>CHtml::link(Yii::t('zii','Home'),array('/admin/home')),'links'=>$this->breadcrumbs)); ?>
			</div>

			<?php echo $content; ?>

		</div>
	</div>
	<footer>
		<?php $this->widget('LanguageSwitch',array('view'=>'application.views.admin.widget.LanguageSwitch'));?>
		<span class="sun">Sun<span class="code">Code</span><span class="cms">.CMS</span> © 2013 - <?=date('Y')?></span>
		<span class="version">
			<?php echo CHtml::decode(Yii::app()->params['app?']['version']); ?>: <?php echo CHtml::decode(Yii::app()->params['app']['cms']['version']); ?>
		</span>
	</footer>
</body>
</html>

protected/views/layouts/loginadmin.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/form.css" />
	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/styles.css" />
	<!-- Иконки -->
	<link rel="stylesheet" type="text/css" href="<?=Yii::app()->getbaseUrl(true)?>/public/css/awesome/css/font-awesome.min.css">
	<!-- Шрифты -->
	<link href='http://fonts.googleapis.com/css?family=Poiret+One&subset=latin,cyrillic' rel='stylesheet' type='text/css'> <!-- 'Poiret One', cursive -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'> <!-- 'Open Sans' -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&subset=cyrillic,cyrillic-ext,latin' rel='stylesheet' type='text/css'><!-- 'Open Sans Condensed', sans-serif -->

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<body>
	<div id="container">
		<div id="mainback">
			<div id="backgr">


			</div>
			
		</div>

		<div id="content" class="contentlogin">
			<div class="heading">
			<h1><?=$this->title; ?></h1>
			</div>

			<?php echo $content; ?>
		</div>
	</div>
	<footer>
		<span class="sun">Sun<span class="code">Code</span><span class="cms">.CMS</span> © 2013</span>
		<br/>
		<span class="version">
			<?php echo CHtml::decode(Yii::app()->params['app?']['version']); ?>: <?php echo CHtml::decode(Yii::app()->params['app']['cms']['version']); ?>
		</span>
	</footer>
</body>
</html>